### PR TITLE
fix(user-agent): search for the SDK package.json from the root

### LINKED ISSUE #9: Module not found error in user-agent
### Description

If I use this module as a dependency of another module, I get an error that `package.json` is not found.
The error was thrown on [this line](https://github.com/commercetools/csv-parser-price/blob/master/src/user-agent.js#L4).

The likely cause is because the package.json in the sdk is being referenced with the assumption that the sdk module will be in the node_modules of this module but that is not the case with npm3 
```js
import sdkPackage from '../node_modules/sphere-node-sdk/package.json'
```

### Expected Behavior

Should work without error.

### Context

I cannot use this module because it crashes the module.

### PR DESCRIPTION
**Pull request by Siilwyn**
Instead of getting the SDK version from the package's JSON file itself get it from the root to fix the usage of this module as a dependency. This comes at the cost of having a less precise version number.

Resolves #9

### CODE REVIEW

File: src/user-agent.js [hunk 1]
```diff
@@ -1,9 +1,8 @@
 import { arch, platform } from 'os'
 
 import modulePackage from '../package.json'
-import sdkPackage from '../node_modules/sphere-node-sdk/package.json'
 
-const sdkInfo = `node-sdk/${sdkPackage.version}`
+const sdkInfo = `node-sdk/${modulePackage.dependencies['sphere-node-sdk']}`
```
Comment (hisabimbola) [inline src/user-agent.js]: you might want to check this out

[load-module-pkg](https://www.npmjs.com/package/load-module-pkg)

Might be a better solution

Comment (Siilwyn) [reply src/user-agent.js]: Doesn't work because it does [the same lookup](https://github.com/jonschlinkert/load-module-pkg/blob/master/index.js#L18) as I did before.
We could do `'../node_modules/sphere-node-sdk/package.json' || '../../node_modules/sphere-node-sdk/package.json'` to fix it though, thoughts on that?

File: src/user-agent.js [hunk 2]
```diff
@@ -1,9 +1,9 @@
 import { arch, platform } from 'os'
+import getPackage from 'load-module-pkg'
 
 import modulePackage from '../package.json'
-import sdkPackage from '../node_modules/sphere-node-sdk/package.json'
 
-const sdkInfo = `node-sdk/${sdkPackage.version}`
+const sdkInfo = `node-sdk/${getPackage('sphere-node-sdk').version}`
```
Comment (hisabimbola) [inline src/user-agent.js]: Refactored this to the sphere-node-utils [here](https://github.com/sphereio/sphere-node-utils/pull/28)

Can we update this then, and see if it works in impex

**Comment by Siilwyn** [comment]
@hisabimbola I can not review my own PR but you forgot to bump up the node-utils version in the dependencies for this to work.

**Review by hisabimbola — APPROVED** [review]
LGTM to us I think 😉

**Comment by Siilwyn** [comment]
👍 squash and merge
https://gist.github.com/Siilwyn/25e2bec26cd7c366bf29fac1e755c939
