### PR TITLE
fix(map-custom-fields): support floating numbers

### LINKED ISSUE #22: Module does not handle floating number
### Description

Running the CLI module with a floating number in the csv returns an error

### Expected Behavior

The module should support floating numbers
### Current Behavior

Using the CLI with this sample CSV
```csv
variant-sku,value.currencyCode,value.centAmount,customType,customField.measureUnit,customField.measureQuantity,customField.basePriceCentAmount,customField.basePriceMeasureQuantity,customField.basePriceMeasureUnit
36814,EUR,5798,Pricing,kg,0.5,498,1,kg
```

Returns an error: 
```
[ '[row 2: Pricing] - The number 0.5 isn\'t valid' ]
```

### PR DESCRIPTION
**Pull request by hisabimbola**
#### Summary

Fixes #22 

#### TODO

- Tests
    - [x] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

File: src/map-custom-fields.js [hunk 1]
```diff
@@ -197,16 +197,16 @@ export default (function MapCustomFields () {
...
       return result
-    const matchedNumber = regEx.exec(rawNo)
-    if (!matchedNumber) {
+    const isNotValidNumber = isNaN(Number(rawNo))
+    if (isNotValidNumber) {
       result.error = `The number ${rawNo} isn't valid`
       return result
     }
-    result.data = parseInt(matchedNumber[0], 10)
+    result.data = parseFloat(rawNo, 10)
```
Comment (Siilwyn) [inline src/map-custom-fields.js]: I'm wondering if it's not safer to store the number parsed with `Number` to test against **and** return. Because now it parses the number in two different ways which might lead unexpected behaviour.

```
Number('023.3')
> 23.3
parseInt('023.3', 10)
> 23

Number('2f3f')
> NaN
parseInt('2f3f', 10)
> 2
```

File: test/map-custom-fields.spec.js [hunk 2]
```diff
@@ -207,6 +207,15 @@ test(`mapCustomFields::mapNumber
 })
 
 test(`mapCustomFields::mapNumber
+  should parse a valid floating number`, (t) => {
```
Comment (Siilwyn) [inline test/map-custom-fields.spec.js:210]: 🎈 💯

**Review by Siilwyn — CHANGES_REQUESTED** [review]
Looking good, just one doubt about the two different parsing methods. 🤔

File: src/map-custom-fields.js (hunk 1 above)
Comment (Siilwyn) [reply src/map-custom-fields.js]:
```
parseFloat('44.jpg', 10)
> 44
```

**Review by Siilwyn — APPROVED** [review]
